### ISSUE TITLE
week 09

### ISSUE THREAD

**Issue by iansannar** [iansannar/cse210-project#1]
# To-do
We need to discuss and answer (to some degree) the following questions in order to establish our goal for this project:
- [ ] **What program are we going to create?** We need to at least think of a general concept.
- [ ] **What technologies will we use?** We mainly need to determine what libraries/modules we will depend on.
- [ ] **What features will we include or exclude?** A [planning guide](https://mmanley29.bitbucket.io/module09/planning_guide.html) has been provided to help us out with this one.
- [ ] **What is your timeline?** We have several deadlines for this project:
    - [ ] **Alpha Release** by March 12, 2021. [Requirements](https://mmanley29.bitbucket.io/module10/alpha_requirements.html); [milestone](https://github.com/iansannar/cse210-project/milestone/1)
    - [ ] **Beta Release** by March 19, 2021. [Requirements](https://mmanley29.bitbucket.io/module11/beta_requirements.html); [milestone](https://github.com/iansannar/cse210-project/milestone/2)
    - [ ] **Release Candidate** by March 26, 2021. [Requirements](https://mmanley29.bitbucket.io/module12/rc_requirements.html); [milestone](https://github.com/iansannar/cse210-project/milestone/3)
    - [ ] **Stable Release** by April 2, 2021. [Requirements](https://mmanley29.bitbucket.io/module13/stable_requirements.html); [milestone](https://github.com/iansannar/cse210-project/milestone/4)

We also need to complete the following tasks:
- [ ] Import the project template to this repository. Currently the [link to the template](https://mmanley29.bitbucket.io/module09/project_template.zip) is dead.
- [ ] Document our plans and answers to the above questions in the `/docs` folder of the project template. Requires the template.

# [Project Requirements](https://mmanley29.bitbucket.io/module09/project_requirements.html)
1. The program may be any type of game or interactive simulation.
2. The program must use classes and objects.
3. The program must use the four principles of object-oriented programming.
4. The program must use the libraries chosen in the course.
5. The program must be delivered through a distributed version control system.
6. The program must be able to be run from the command line.
7. The program must be entered in the end-of-course contest.
